// apps/dashboard/src/routes/rankings/+page.svelte
<script lang="ts">
  let { data } = $props();
</script>

<svelte:head>
  <title>Rankings - Nazuna Bot</title>
</svelte:head>

<main class="rankings-page">
  <header class="page-header">
    <h1>Rankings</h1>
    <p class="page-subtitle">The most popular and top-rated characters</p>
  </header>
  
  <!-- Tabs -->
  <div class="tabs">
    <a 
      href="/rankings?type=popularity&page=1" 
      class="tab"
      class:active={data.currentType === 'popularity'}
    >
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
        <circle cx="12" cy="12" r="3"/>
      </svg>
      Popularity
    </a>
    <a 
      href="/rankings?type=ratings&page=1" 
      class="tab"
      class:active={data.currentType === 'ratings'}
    >
      <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2">
        <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
      </svg>
      Ratings
    </a>
    <a 
      href="/rankings?type=combined&page=1" 
      class="tab"
      class:active={data.currentType === 'combined'}
    >
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/>
        <polyline points="17 6 23 6 23 12"/>
      </svg>
      Combined
    </a>
  </div>
  
  {#if data.source === 'mock'}
    <div class="mock-banner">
      <span class="mock-badge">DEMO DATA</span>
      <span>API unavailable. Showing mock rankings.</span>
    </div>
  {/if}
  
  <!-- Rankings List -->
  <div class="rankings-list">
    {#each data.rankings as char, index (char.id ?? char.anilistId ?? `rank-${index}`)}
      <div class="ranking-item neobrutal-card">
        <div class="rank" class:top-rank={index < 3}>#{(data.pagination.page - 1) * data.pagination.limit + index + 1}</div>
        
        <div class="item-image">
          <img 
            src={char.imageUrl || char.image || `https://picsum.photos/seed/${char.name}/600/800`}
            alt={char.name}
            referrerPolicy="no-referrer"
          />
        </div>
        
        <div class="item-info">
          <h3>{char.name}</h3>
          <p>{char.series || char.work?.title || 'Unknown'}</p>
        </div>
        
        <div class="item-stats">
          <div class="stat">
            <span class="stat-label">Score</span>
            <span class="stat-value">{(char.score || char.rating || 0).toFixed(1)}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Popularity</span>
            <span class="stat-value">{(char.popularity || 0).toLocaleString()}</span>
          </div>
        </div>
        
        <a href="/characters/{char.id || char.anilistId}" class="view-btn">
          VIEW
        </a>
      </div>
    {/each}
  </div>
  
  <!-- Pagination -->
  {#if data.pagination.totalPages > 1}
    <div class="pagination">
      {#if data.pagination.page > 1}
        <a href="/rankings?type={data.currentType}&page={data.pagination.page - 1}" class="page-btn">
          Previous
        </a>
      {/if}
      
      <span class="page-info">
        Page {data.pagination.page} of {data.pagination.totalPages}
      </span>
      
      {#if data.pagination.page < data.pagination.totalPages}
        <a href="/rankings?type={data.currentType}&page={data.pagination.page + 1}" class="page-btn">
          Next
        </a>
      {/if}
    </div>
  {/if}
</main>

<style>
  .rankings-page {
    display: flex;
    flex-direction: column;
    gap: 48px;
  }
  
  .page-header {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  
  .page-header h1 {
    font-size: 48px;
    font-weight: 900;
    text-transform: uppercase;
    letter-spacing: -0.02em;
  }
  
  .page-subtitle {
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.15em;
    color: var(--text-secondary);
  }
  
  .mock-banner {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 12px 16px;
    background: var(--bg-secondary);
    border: 2px solid var(--accent-yellow);
  }
  
  .mock-badge {
    font-size: 9px;
    font-weight: 900;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    background: var(--accent-yellow);
    color: #000;
    padding: 2px 6px;
    border: 1px solid #000;
  }
  
  .tabs {
    display: flex;
    flex-wrap: wrap;
    gap: 16px;
    padding-bottom: 32px;
    border-bottom: var(--border-brutal);
  }
  
  .tab {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 12px 24px;
    font-weight: 900;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: -0.02em;
    border: var(--border-brutal);
    background: transparent;
    color: white;
    text-decoration: none;
    transition: all var(--transition-fast);
  }
  
  .tab:hover {
    background: rgba(255, 255, 255, 0.05);
  }
  
  .tab.active {
    background: var(--accent-purple);
    color: #000;
    box-shadow: var(--shadow-brutal);
  }
  
  .rankings-list {
    display: flex;
    flex-direction: column;
    gap: 24px;
  }
  
  .ranking-item {
    display: flex;
    flex-direction: column;
    padding: 16px;
    gap: 16px;
    align-items: center;
  }
  
  @media (min-width: 768px) {
    .ranking-item {
      flex-direction: row;
    }
  }
  
  .rank {
    font-size: 32px;
    font-weight: 900;
    letter-spacing: -0.02em;
    color: var(--text-secondary);
    width: 64px;
    text-align: center;
  }
  
  .rank.top-rank {
    color: var(--accent-yellow);
  }
  
  .item-image {
    width: 96px;
    height: 96px;
    border: var(--border-brutal);
    overflow: hidden;
    flex-shrink: 0;
  }
  
  .item-image img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  
  .item-info {
    flex: 1;
    text-align: center;
  }
  
  @media (min-width: 768px) {
    .item-info {
      text-align: left;
    }
  }
  
  .item-info h3 {
    font-size: 20px;
    font-weight: 900;
    text-transform: uppercase;
    letter-spacing: -0.02em;
  }
  
  .item-info p {
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: var(--accent-purple);
  }
  
  .item-stats {
    display: flex;
    gap: 32px;
  }
  
  .stat {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 4px;
  }
  
  .stat-label {
    font-size: 9px;
    font-weight: 900;
    text-transform: uppercase;
    letter-spacing: -0.02em;
    color: var(--text-secondary);
  }
  
  .stat-value {
    font-size: 18px;
    font-weight: 900;
    letter-spacing: -0.02em;
  }
  
  .view-btn {
    padding: 8px 24px;
    background: var(--accent-blue);
    color: #000;
    font-weight: 700;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    border: var(--border-brutal);
    box-shadow: var(--shadow-brutal);
    transition: all var(--transition-fast);
    text-decoration: none;
  }
  
  .view-btn:hover {
    box-shadow: none;
    transform: translate(2px, 2px);
  }
  
  .pagination {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 16px;
    padding: 32px 0;
  }
  
  .page-btn {
    padding: 12px 24px;
    background: var(--bg-card);
    border: var(--border-brutal);
    border-radius: var(--radius-md);
    font-weight: 700;
    color: var(--text-primary);
    text-decoration: none;
    box-shadow: var(--shadow-brutal-sm);
    transition: all var(--transition-fast);
  }
  
  .page-btn:hover {
    border-color: var(--accent-blue);
    transform: translate(-2px, -2px);
    box-shadow: var(--shadow-brutal);
  }
  
  .page-info {
    font-size: 14px;
    color: var(--text-secondary);
  }
</style>

// dashboard-reference/src/pages/Rankings.tsx
import React, { useState } from 'react';
import { motion } from 'motion/react';
import { Trophy, Star, TrendingUp, Eye } from 'lucide-react';
import { MOCK_CHARACTERS } from '../data';
import { Link } from 'react-router-dom';

export default function Rankings() {
  const [activeTab, setActiveTab] = useState<'popularity' | 'ratings' | 'combined'>('popularity');

  const sortedCharacters = [...MOCK_CHARACTERS].sort((a, b) => {
    if (activeTab === 'popularity') return (b.views || 0) - (a.views || 0);
    if (activeTab === 'ratings') return b.rating - a.rating;
    return (b.views || 0) * b.rating - (a.views || 0) * a.rating;
  });

  return (
    <main className="pt-24 pb-20 px-4 max-w-7xl mx-auto space-y-12">
      <header className="space-y-4">
        <h1 className="text-5xl font-black uppercase tracking-tighter">Rankings</h1>
        <p className="text-text-secondary font-bold uppercase tracking-widest">The most popular and top-rated characters</p>
      </header>

      <div className="flex flex-wrap gap-4 border-b-brutal pb-8">
        <TabButton 
          active={activeTab === 'popularity'} 
          onClick={() => setActiveTab('popularity')} 
          icon={<Eye size={18} />} 
          label="Popularity" 
        />
        <TabButton 
          active={activeTab === 'ratings'} 
          onClick={() => setActiveTab('ratings')} 
          icon={<Star size={18} />} 
          label="Ratings" 
        />
        <TabButton 
          active={activeTab === 'combined'} 
          onClick={() => setActiveTab('combined')} 
          icon={<TrendingUp size={18} />} 
          label="Combined" 
        />
      </div>

      <div className="space-y-6">
        {sortedCharacters.map((char, index) => (
          <motion.div 
            key={char.id}
            className="neobrutal-card p-4 flex flex-col md:flex-row items-center gap-6"
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ delay: index * 0.05 }}
            viewport={{ once: true }}
          >
            <div className={`text-4xl font-black tracking-tighter w-16 text-center ${index < 3 ? 'text-accent-yellow' : 'text-text-secondary'}`}>
              #{index + 1}
            </div>

            <div className="w-24 h-24 flex-shrink-0 border-brutal overflow-hidden">
              <img 
                src={char.image} 
                alt={char.name} 
                className="w-full h-full object-cover"
                referrerPolicy="no-referrer"
              />
            </div>

            <div className="flex-1 space-y-1 text-center md:text-left">
              <h3 className="text-2xl font-black uppercase tracking-tighter">{char.name}</h3>
              <p className="text-sm font-bold text-accent-purple uppercase tracking-widest">{char.series}</p>
            </div>

            <div className="flex gap-8">
              <StatItem label="Views" value={char.views?.toLocaleString() || '0'} />
              <StatItem label="Rating" value={char.rating.toFixed(1)} />
            </div>

            <Link 
              to={`/characters/${char.id}`}
              className="px-6 py-2 bg-accent-blue text-black font-bold border-brutal shadow-brutal hover:shadow-none hover:translate-x-1 hover:translate-y-1 transition-all"
            >
              VIEW
            </Link>
          </motion.div>
        ))}
      </div>
    </main>
  );
}

function TabButton({ active, onClick, icon, label }: { active: boolean, onClick: () => void, icon: React.ReactNode, label: string }) {
  return (
    <button 
      onClick={onClick}
      className={`flex items-center gap-2 px-6 py-3 border-brutal font-black uppercase tracking-tighter transition-all ${active ? 'bg-accent-purple text-black shadow-brutal' : 'hover:bg-white/5'}`}
    >
      {icon}
      {label}
    </button>
  );
}

function StatItem({ label, value }: { label: string, value: string }) {
  return (
    <div className="text-center">
      <p className="text-[10px] font-black uppercase tracking-tighter text-text-secondary">{label}</p>
      <p className="text-xl font-black tracking-tighter">{value}</p>
    </div>
  );
}
